### ISSUE TITLE
undefined method 'name' for nil:NilClass

### ISSUE THREAD

**Issue by ethanclevenger91** [Mixd/wp-deploy#113]
Looks similar to #107 but not quite the same. When doing `bundle exec cap staging wp:setup:local --trace` I get the following error:

```
** Invoke staging (first_time)
** Execute staging
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke wp:setup:local (first_time)
** Execute wp:setup:local
cap aborted!
NoMethodError: undefined method `name' for nil:NilClass
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sshkit-1.7.1/lib/sshkit/host.rb:29:in `initialize'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sshkit-1.7.1/lib/sshkit/backends/local.rb:10:in `new'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sshkit-1.7.1/lib/sshkit/backends/local.rb:10:in `initialize'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/capistrano-3.4.0/lib/capistrano/dsl.rb:59:in `new'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/capistrano-3.4.0/lib/capistrano/dsl.rb:59:in `run_locally'
Q:/dev/deploy/lib/capistrano/tasks/wp.cap:84:in `block (3 levels) in <top (required)>'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
C:/Ruby200-x64/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/capistrano-3.4.0/lib/capistrano/application.rb:15:in `run'
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/capistrano-3.4.0/bin/cap:3:in `<top (required)>'
C:/Ruby200-x64/bin/cap:22:in `load'
C:/Ruby200-x64/bin/cap:22:in `<main>'
Tasks: TOP => wp:setup:local
```

Obviously that's a lot. I can't even begin to debug, but looks to be SSHKit related?

On Windows 10, FWIW

**Comment by TheAggressive** [comment]
I also got this error. in your Gemfile.lock and change sshkit version to (1.9.0) that goes away but then a new error comes up ad shown below.

```
$ bundle exec cap staging wp:setup:local --trace
** Invoke staging (first_time)
** Execute staging
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke wp:setup:local (first_time)
** Execute wp:setup:local
cap aborted!
Errno::ENOENT: No such file or directory - /usr/bin/env wp core install --url='http://testing.dev' --title='This Better Work' --admin_user='Great All Mighty' --admin_password='ooxEczBzlXdpxZaZru' --admin_email='test@test.com'
C:/Ruby21-x64/lib/ruby/2.1.0/open3.rb:193:in `spawn'
C:/Ruby21-x64/lib/ruby/2.1.0/open3.rb:193:in `popen_run'
C:/Ruby21-x64/lib/ruby/2.1.0/open3.rb:93:in `popen3'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sshkit-1.9.0/lib/sshkit/backends/local.rb:41:in `execute_command'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sshkit-1.9.0/lib/sshkit/backends/abstract.rb:137:in `block in create_command_and_execute'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sshkit-1.9.0/lib/sshkit/backends/abstract.rb:137:in `tap'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sshkit-1.9.0/lib/sshkit/backends/abstract.rb:137:in `create_command_and_execute'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sshkit-1.9.0/lib/sshkit/backends/abstract.rb:69:in `execute'
C:/Websites/www/theaggressive/htdocs/lib/capistrano/tasks/wp.cap:107:in `block (4 levels) in <top (required)>'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sshkit-1.9.0/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/sshkit-1.9.0/lib/sshkit/backends/abstract.rb:29:in `run'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/capistrano-3.4.0/lib/capistrano/dsl.rb:59:in `run_locally'
C:/Websites/www/theaggressive/htdocs/lib/capistrano/tasks/wp.cap:84:in `block (3 levels) in <top (required)>'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
C:/Ruby21-x64/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/capistrano-3.4.0/lib/capistrano/application.rb:15:in `run'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/capistrano-3.4.0/bin/cap:3:in `<top (required)>'
C:/Ruby21-x64/bin/cap:23:in `load'
C:/Ruby21-x64/bin/cap:23:in `<main>'
Tasks: TOP => wp:setup:local
  INFO [b345198f] Running /usr/bin/env wp core install --url='http://testing.dev' --title='The Better Work' --admin_user='Great All Mighty' --admin_password='ooxEczBzlXdpxZaZru' --admin_email='test@test.com' as Shawn@localhost
```

**Comment by lukewhitehouse** [comment]
@ethanclevenger91 @TheAggressive Hey guys, so it seems you're both having Windows trouble.

Can you perform the following commands and let me know what each says:

```
$ ruby -v
$ wp --info
$ php -v
```

They should all show the correct versions of ruby/wpcli/php you're running.

**Comment by ethanclevenger91** [comment]
Thanks for the prompt response!

WP-CLI v. 0.22.0
Ruby 2.0.0p645
PHP 5.6.16

Realizing that Ruby was a bit dated, I upgraded to 2.3.0 with the same output.

**Comment by TheAggressive** [comment]
PHP 5.5.24 
ruby 2.1.3p242
WP-CLI version: 0.23.0-alpha

**Comment by lukewhitehouse** [comment]
Hi @TheAggressive & @ethanclevenger91 sorry for the late reply. Still seeing issues or manage to find a fix?

**Comment by lukewhitehouse** [comment]
Archiving, please create a new issue if your problem persists.

**Comment by klizas** [comment]
I find a way why it happens. Check your database.yml file identation. It should be 4 spaces.
