### ISSUE TITLE
Error: Strange wp-config.php file

### ISSUE THREAD

**Issue by ttomdewit** [Mixd/wp-deploy#119]
I have a DigitalOcean droplet running on Ubuntu 16.04 with PHP 7, Git and WP-CLI and have been able to successfully push to both production and staging environments with `$ bundle exec cap staging deploy`.

Unfortunately, when trying to push my database to my remote environments with `$ bundle exec cap staging db:push` the following error shows up (with `--trace`):

<details>
```
Running /usr/bin/env wp db import /var/www/dev.tomdewit.com/public_html/shared/db_backups/201671782431.sql as admin@XXX.XXX.XXX.XXX
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as admin@XXX.XXX.XXX.XXX: wp exit status: 1
wp stdout: Nothing written
wp stderr: Error: Strange wp-config.php file: wp-settings.php is not loaded directly.
/Users/tomdewit/.rvm/gems/ruby-2.2.2/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:16:in `rescue in block (2 levels) in execute'
/Users/tomdewit/.rvm/gems/ruby-2.2.2/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
SSHKit::Command::Failed: wp exit status: 1
wp stdout: Nothing written
wp stderr: Error: Strange wp-config.php file: wp-settings.php is not loaded directly.
/Users/tomdewit/.rvm/gems/ruby-2.2.2/gems/sshkit-1.7.1/lib/sshkit/command.rb:95:in `exit_status='
/Users/tomdewit/.rvm/gems/ruby-2.2.2/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:179:in `block in _execute'
/Users/tomdewit/.rvm/gems/ruby-2.2.2/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:133:in `tap'
/Users/tomdewit/.rvm/gems/ruby-2.2.2/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:133:in `_execute'
/Users/tomdewit/.rvm/gems/ruby-2.2.2/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:66:in `execute'
/Users/tomdewit/Sites/wp-deploy/lib/capistrano/tasks/db.cap:123:in `block (4 levels) in <top (required)>'
/Users/tomdewit/.rvm/gems/ruby-2.2.2/gems/sshkit-1.7.1/lib/sshkit/backends/abstract.rb:77:in `within'
/Users/tomdewit/Sites/wp-deploy/lib/capistrano/tasks/db.cap:122:in `block (3 levels) in <top (required)>'
/Users/tomdewit/.rvm/gems/ruby-2.2.2/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/Users/tomdewit/.rvm/gems/ruby-2.2.2/gems/sshkit-1.7.1/lib/sshkit/backends/netssh.rb:54:in `run'
/Users/tomdewit/.rvm/gems/ruby-2.2.2/gems/sshkit-1.7.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
Tasks: TOP => db:push
```
</details>

**Comment by lukewhitehouse** [comment]
@ttomdewit i think this may be because you're using PHP7. The `db` commands use wpcli as you know so I reckon wpcli is not compatible with php7. Can you confirm that?

**Comment by ttomdewit** [comment]
It looks like WP-CLI is experiencing some bugs with PHP7, yes. I'll see if I can downgrade to PHP 5.6 and test again.

**Comment by ttomdewit** [comment]
@lukewhitehouse Can you share the details you've been using with your server(s)?

**Comment by lukewhitehouse** [comment]
@ttomdewit Of course :) Currently:

- wpcli 0.23.*
- PHP 5.6.*
- Apache 2.4 (I think?)

**Comment by lukewhitehouse** [comment]
@ttomdewit still getting a problem Tom?

**Comment by ttomdewit** [comment]
@lukewhitehouse I've been busy dealing with other requirements. Will pick this up this month and I'll reopen a ticket when and if necessary.

Thanks for your help so far.
