### ISSUE TITLE
SSHKit::Runner::ExecuteError: Exception while executing as user@domain: git exit status: 1

### ISSUE THREAD

**Issue by jogoool** [Mixd/wp-deploy#150]
Hi 
After I add ssh port 2222 (Hostgator ssh port) to my staging configuration I face SSHKit Execution Error and working tree already exist. I try to deploy the site to different host that using default ssh port and it working well. 

staging.rb 
```
# The environment's server credentials
server 'domain', user: 'user', roles: %w(web app db), port: 2222
```

Error: 
```
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as user@domain: git exit status: 1
git stdout: Submodule 'wordpress' () registered for path 'wordpress'
fatal: working tree '/path/to/directory/releases/20171103005243' already exists.
Clone of 'git://core.git.wordpress.org/' into submodule path 'wordpress' failed
git stderr: Nothing written
/Users/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.13.1/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute'
/Users/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.13.1/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
SSHKit::Command::Failed: git exit status: 1
git stdout: Submodule 'wordpress' () registered for path 'wordpress'
fatal: working tree '/path/to/directory/releases/20171103021649' already exists.
Clone of 'git://core.git.wordpress.org/' into submodule path 'wordpress' failed
git stderr: Nothing written
/Users/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.13.1/lib/sshkit/command.rb:100:in `exit_status='
/Users/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.13.1/lib/sshkit/backends/netssh.rb:165:in `execute_command'
/Users/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.13.1/lib/sshkit/backends/abstract.rb:141:in `block in create_command_and_execute'
/Users/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.13.1/lib/sshkit/backends/abstract.rb:141:in `tap'
/Users/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.13.1/lib/sshkit/backends/abstract.rb:141:in `create_command_and_execute'
/Users/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.13.1/lib/sshkit/backends/abstract.rb:74:in `execute'
/Users/jogool/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/capistrano-git-with-submodules-2.0.3/lib/capistrano/scm/git-with-submodules.rb:31:in `block (6 levels) in define_tasks'
/Users/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.13.1/lib/sshkit/backends/abstract.rb:85:in `within'
/Users/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/capistrano-git-with-submodules-2.0.3/lib/capistrano/scm/git-with-submodules.rb:26:in `block (5 levels) in define_tasks'
/Users/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.13.1/lib/sshkit/backends/abstract.rb:93:in `with'
/Users/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/capistrano-git-with-submodules-2.0.3/lib/capistrano/scm/git-with-submodules.rb:21:in `block (4 levels) in define_tasks'
/Users/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.13.1/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
/Users/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.13.1/lib/sshkit/backends/abstract.rb:29:in `run'
/Users/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.13.1/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => git:submodules:create_release
The deploy has failed with an error: Exception while executing as user@domain: git exit status: 1
git stdout: Submodule 'wordpress' () registered for path 'wordpress'
fatal: working tree '/path/to/directory/releases/20171103021649' already exists.
Clone of 'git://core.git.wordpress.org/' into submodule path 'wordpress' failed
git stderr: Nothing written
** Invoke deploy:failed (first_time)
** Execute deploy:failed

```

any idea why this happen!

**Comment by vukhanhtruong** [comment]
I met the same issue. I have removed wordpress submodule then copy wordpress folder to wp-deploy.

**Comment by lustremedia** [comment]
It is most probably a git issue:
I use following as a submodule, not using ssh but https to grab wordpress

 [submodule "wordpress"]
	path = wordpress
	url = https://github.com/WordPress/WordPress.git

**Comment by jogoool** [comment]
https not working also. 
any update or help

**Comment by DrizzlyOwl** [comment]
Hello, apologies for the delay. If you were to run `cache:repo:purge` then try to re-deploy that may fix your issue. Could you also please let me know what is written in your .gitmodules file?

**Comment by lustremedia** [comment]
@jogoool I am currently doing an overhaul of wp-deploy. Look here: https://github.com/lustremedia/wp-deploy-easy 
it should make things easier ...
