### ISSUE TITLE
Rake GemNotFound on remote

### ISSUE THREAD

**Issue by nanashiRei** [Mixd/wp-deploy#57]
When i try to push the repo to my server i get this:

```Counting objects: 40, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (37/37), done.
Writing objects: 100% (40/40), 14.14 KiB | 0 bytes/s, done.
Total 40 (delta 6), reused 0 (delta 0)
remote: /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find rake-10.3.2 in any of the sources (Bundler::GemNotFound)
remote: 	from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/spec_set.rb:85:in `map!'
remote: 	from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/spec_set.rb:85:in `materialize'
remote: 	from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/definition.rb:132:in `specs'
remote: 	from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/definition.rb:177:in `specs_for'
remote: 	from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/definition.rb:166:in `requested_specs'
remote: 	from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/environment.rb:18:in `requested_specs'
remote: 	from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/runtime.rb:13:in `setup'
remote: 	from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler.rb:122:in `setup'
remote: 	from /usr/local/lib/ruby/gems/2.1.0/gems/bundler-1.7.12/lib/bundler/setup.rb:17:in `<top (required)>'
remote: 	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
remote: 	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
To https://gitlitio.us/nanashiRei/new-project.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://gitlitio.us/nanashiRei/new-project.git'```

I have no idea what that means.

**Comment by nanashiRei** [comment]
the paste looks aweful.. here http://pastie.org/private/z6vgnwjafyf3fi9p6u0r8w same output

**Comment by lukewhitehouse** [comment]
Hi @nanashiRei, it sounds like theres a problem with Bundler, can you check if you have it installed on your system and that you've ran `bundle install` within your project.

**Comment by nanashiRei** [comment]
I'm on Mac, so it's installed. I did double check to see if that's true aswell. And doing what you said results in what i posted, exactly.

**Comment by lukewhitehouse** [comment]
@nanashiRei Assuming you're right and [Bundler](http://bundler.io/) is installed on your system then the issue will lie with the Github repo being out of sync with the repo on your server. Try the following:

1. SSH into your environment
2. Navigate to your site folder.
3. Delete the `repo` folder and everything within it
4. Deploy your site again

With any luck, that should fix your issue. Let me know.
