### ISSUE TITLE
git rev-parse --short HEAD stdout: Nothing written

### ISSUE THREAD

**Issue by omsoft** [Mixd/wp-deploy#67]
Hello,
the capistrano deployment fails with this error:

```
$ bundle exec cap production wp:setup:remote
 INFO [b561e4b9] Running /usr/bin/env mkdir -p /tmp/myapplication/ on MYIP_ADDRESS
 INFO [b561e4b9] Finished in 0.113 seconds with exit status 0 (successful).
 INFO Uploading /tmp/myapplication/git-ssh.sh 100.0%
 INFO [cdf243ea] Running /usr/bin/env chmod +x /tmp/myapplication/git-ssh.sh on MYIP_ADDRESS
 INFO [cdf243ea] Finished in 0.098 seconds with exit status 0 (successful).
 INFO [984338f6] Running /usr/bin/env mkdir -p /tmp/myapplication/ on MYIP_ADDRESS
 INFO [984338f6] Finished in 0.113 seconds with exit status 0 (successful).
 INFO Uploading /tmp/myapplication/git-ssh.sh 100.0%
 INFO [f3b4707c] Running /usr/bin/env chmod +x /tmp/myapplication/git-ssh.sh on MYIP_ADDRESS
 INFO [f3b4707c] Finished in 0.101 seconds with exit status 0 (successful).
 INFO [28cbffb2] Running /usr/bin/env mkdir -pv /containers/30025/sites/myapplication/shared /containers/30025/sites/myapplication/releases on MYIP_ADDRESS
 INFO [28cbffb2] Finished in 0.147 seconds with exit status 0 (successful).
 INFO [dec3eba0] Running /usr/bin/env mkdir -pv /containers/30025/sites/myapplication/shared/content/uploads on 148.251.3.181
 INFO [dec3eba0] Finished in 0.102 seconds with exit status 0 (successful).
 INFO [875c0694] Running /usr/bin/env mkdir -pv /containers/30025/sites/myapplication/shared /containers/30025/sites/myapplication/shared on MYIP_ADDRESS
 INFO [875c0694] Finished in 0.104 seconds with exit status 0 (successful).
 INFO [59829d7b] Running /usr/bin/env touch /containers/30025/sites/myapplication/shared/wp-config.php on MYIP_ADDRESS
 INFO [59829d7b] Finished in 0.101 seconds with exit status 0 (successful).
 INFO [1892d55e] Running /usr/bin/env touch /containers/30025/sites/myapplication/shared/.htaccess on MYIP_ADDRESS
 INFO [1892d55e] Finished in 0.091 seconds with exit status 0 (successful).
 INFO The repository mirror is at /containers/30025/sites/myapplication/repo
 INFO The repository mirror is at /containers/30025/sites/myapplication/repo
cap aborted!
cd /containers/30025/sites/myapplication/repo && git rev-parse --short HEAD stdout: Nothing written
cd /containers/30025/sites/myapplication/repo && git rev-parse --short HEAD stderr: Nothing written
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/sshkit-1.3.0/lib/sshkit/command.rb:94:in `exit_status='
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/sshkit-1.3.0/lib/sshkit/backends/netssh.rb:142:in `block (4 levels) in _execute'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/net-ssh-2.8.0/lib/net/ssh/connection/channel.rb:551:in `call'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/net-ssh-2.8.0/lib/net/ssh/connection/channel.rb:551:in `do_request'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:561:in `channel_request'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:465:in `dispatch_incoming_packets'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:221:in `preprocess'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:205:in `process'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:169:in `block in loop'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:169:in `loop'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:169:in `loop'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/net-ssh-2.8.0/lib/net/ssh/connection/channel.rb:269:in `wait'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/sshkit-1.3.0/lib/sshkit/backends/netssh.rb:164:in `block (2 levels) in _execute'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/net-ssh-2.8.0/lib/net/ssh/connection/channel.rb:514:in `call'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/net-ssh-2.8.0/lib/net/ssh/connection/channel.rb:514:in `do_open_confirmation'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:545:in `channel_open_confirmation'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:465:in `dispatch_incoming_packets'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:221:in `preprocess'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:205:in `process'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:169:in `block in loop'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:169:in `loop'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/net-ssh-2.8.0/lib/net/ssh/connection/session.rb:169:in `loop'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/sshkit-1.3.0/lib/sshkit/backends/netssh.rb:166:in `block in _execute'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/sshkit-1.3.0/lib/sshkit/backends/netssh.rb:123:in `tap'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/sshkit-1.3.0/lib/sshkit/backends/netssh.rb:123:in `_execute'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/sshkit-1.3.0/lib/sshkit/backends/netssh.rb:76:in `capture'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/capistrano-3.1.0/lib/capistrano/dsl.rb:59:in `fetch_revision'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/capistrano-3.1.0/lib/capistrano/dsl.rb:30:in `capturing_revisions'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/capistrano-3.1.0/lib/capistrano/tasks/git.rake:52:in `block (4 levels) in <top (required)>'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/sshkit-1.3.0/lib/sshkit/backends/abstract.rb:81:in `within'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/capistrano-3.1.0/lib/capistrano/tasks/git.rake:51:in `block (3 levels) in <top (required)>'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/sshkit-1.3.0/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/sshkit-1.3.0/lib/sshkit/backends/netssh.rb:54:in `run'
/home/mattia/.rvm/gems/ruby-2.0.0-p598/gems/sshkit-1.3.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => git:create_release => git:update
(See full trace by running task with --trace)
The deploy has failed with an error: #<SSHKit::Command::Failed: cd /containers/30025/sites/myapplication/repo && git rev-parse --short HEAD stdout: Nothing written
cd /containers/30025/sites/myapplication/repo && git rev-parse --short HEAD stderr: Nothing written
```

I previously pushed the repository by doing "git push origin master". This is the configuration:

deploy.rb
set :repo_url, "30025@MYIP_ADDRESS:/containers/30025/gitrepository/myapplication.git"

production.rb
set :deploy_to, "/containers/30025/sites/myapplication"

He did set up "repo" and other folders under /containers/30025/sites/myapplication but it seems it's not able to copy the git repository.

Any idea?

**Comment by omsoft** [comment]
I had to reinitialize the local git repo.
